# -*- coding: utf-8 -*-
"""GenerateInputForKnapSack

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1umQMx3Sw4UiY18q1Qb0544fUZVXFWtF_
"""

import random

def generate_input_file(filename, num_items, max_capacity):
    with open(filename, 'w') as file:
        file.write(f"{num_items}\n")
        for _ in range(num_items):
            weight = random.randint(1, 100)  # Random weight between 1 and 100
            value = random.randint(1, 500)  # Random value between 1 and 500
            file.write(f"{weight} {value}\n")
        file.write(f"{max_capacity}\n")


# Generate input files for testing with unique filenames
generate_input_file("./testcase/knapsack_25_items.txt", 25, 1000)
generate_input_file("./testcase/knapsack_50_items.txt", 50, 2000)
generate_input_file("./testcase/knapsack_100_items.txt", 100, 4000)
generate_input_file("./testcase/knapsack_500_items.txt", 500, 8000)
generate_input_file("./testcase/knapsack_1000_items.txt", 1000, 10000)



